version: '3.7'

services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8085:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-option json-column
    networks:
      - formify-dev
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: formify
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - formify-dev

  redis:
    image: redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - formify-dev

networks:
  formify-dev:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
