package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"time"

	gqlmodel "github.com/TrySquadDF/formify/api-gql/internal/delivery/gql/graph/model"
)

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (*gqlmodel.Ping, error) {
	return &gqlmodel.Ping{
		Timestamp: time.Now().Format(time.RFC3339),
		Message:   "pong",
	}, nil
}
